services:
  auth:
    build: 
      context: ..
      dockerfile: dockerfile
    image: lordlumineer/eventkit-auth:0.5.0
    volumes:
      - /app/eventkit/auth/db:/server/db
    ports:
      - target: 80
        published: "20102"
    restart: always
    environment:
      ADMIN_EMAIL: $ADMIN_EMAIL

      DATABASE_HOST: $DATABASE_HOST # "192.168.56.1"
      DATABASE_PORT: $DATABASE_PORT # "20000"
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD

      EMAIL_SMTP_SERVER: "smtp-mail.outlook.com"
      EMAIL_SMTP_PORT: 587
      EMAIL_ADDRESS: "eventkit@outlook.com"
      EMAIL_PASSWORD: $EMAIL_PASSWORD

      JWT_SECRET: $JWT_SECRET
      JWT_MAIN_SERVICE_SECRET: $JWT_MAIN_SERVICE_SECRET
      JWT_ISSUER: "https://id.eventkit.stream/oauth2"

      TWITCH_CLIENT_ID: $TWITCH_CLIENT_ID
      TWITCH_CLIENT_SECRET: $TWITCH_CLIENT_SECRET
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET