FROM python:3.12.3-alpine AS production-stage
RUN python -m pip install --upgrade pip
WORKDIR /server
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY . .

EXPOSE 81
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "81"]
