name: Continuous Linting

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
          cache: 'pip'
      
      - name: Install Dependencies
        run: |
          cd server
          pip install -r requirements.txt
          cd test
          pip install -r requirements.txt

      - name: Run Pylint
        run: |
          cd server
          pylint --disable=R,C .
